# Greedy 문제

### 모험가 길드

한 마을에 모험가가 N명 있습니다. 모험가 길드에서는 N명의 모험가를 대상으로 '공포도'를 측정했는데,<br>
'공포도'가 높은 모험가는 쉽게 공포를 느껴 위험 상황에서 제대로 대처할 능력이 떨어진다.<br>

공포도가 X인 모험가는 반드시 X명 이상으로 구성한 모험가 그룹에 참여해야 여행을 떠날 수 있다.<br>
이때 최대로 떠날 수 있는 모험가 그룹의 수를 구하는 프로그램 작성

In [4]:
N = int(input())
M = list(map(int, input().split()))

M.sort()
print(M)

[1, 2, 2, 2, 3]


In [5]:
num_of_group = 0
while M:
    num_of_member_of_group = M.pop()

    for _ in range(num_of_member_of_group - 1):
        if M: M.pop()
        else: break
    else:
        num_of_group += 1

print(num_of_group)

2


### 해결 전략

겁쟁이들은 겁쟁이들을 최대한 많이 모으고 강한 모험가들은 최대한 조금씩 보내야한다.<br>
따라서 겁쟁이들부터 강한 모험가까지 일렬로 줄을 세워 순서대로 조건에 맞추어 그룹을 지으면 된다.<br>

# 곱하기 혹은 더하기

각 자리가 숫자 (0부터 9)로만 이루어진 문자열 S가 주어졌을 때, 왼쪽부터 오른쪽으로 하나씩 모든 숫자를 확인하며<br>
숫자 사이에 'x'혹은 '+'연산자를 넣어 결과적으로 만들어질 수 있는 가장 큰 수를 구하는 프로그램 작성<br>

단 모든 연산은 왼쪽에서 오른쪽 순서대로 이루어진다.

In [12]:
S = list(map(int, list(input())))

result = 0
for n in S:
    result = max(result + n, result * n)
print(result)

544320


### 해결 전략
+, * 둘 다 해봐서 더 큰 결과가 결과

# 문자열 뒤집기

0과 1로만 이루어진 문자열 S가 있을 때 연속된 인덱스들의 값만을 뒤집을 수 있다. (0 -> 1 or 1 -> 0)
이때 최소한의 행동으로 모두 같은 숫자를 만들 때, 최소한의 수를 구하시오

In [17]:
S = list(map(int, list(input())))

num = [0, 0]
before_bit = S[0]
num[before_bit] += 1
for bit in S:
    if bit != before_bit:
        num[bit] += 1
    before_bit = bit

print(min(num))

[1, 1]
[2, 1]
[2, 2]
[3, 2]
[3, 3]
[4, 3]
[4, 4]
[5, 4]
[5, 5]
[6, 5]
[6, 6]
[7, 6]
[7, 7]
[8, 7]
[8, 8]
[9, 8]
[9, 9]
[10, 9]
[10, 10]
[11, 10]
[11, 11]
[12, 11]
[12, 12]
[13, 12]
[13, 13]
[14, 13]
[14, 14]
14


### 해결 전략

각 비트들의 그룹의 개수를 세어 작은 그룹을 가진 수를 리턴

# 만들 수 없는 금액

N개의 동전을 이용하여 만들수 없는 정수 금액중 최솟값을 구하는 프로그램

In [141]:
n = int(input())
coins = list(map(int, input().split()))
coins.sort()

target = 1
for coin in coins:
    if target < coin:
        break
    else:
        target += coin

print(target)

8


# 볼링공 고르기

A, B 두 사람이 볼링을 치는데 N개의 볼링공, 1부터 M의 무게를 갖는 볼링공이 있다.<br>
각 볼링공은 무게가 다르더라도 서로 다른 볼링공이며 서로 무게가 다른 볼링공으로 볼링을 치려고 한다.<br>
이때 각자 서로 고를 수 있는 볼링공 set의 경우의 갯수를 구하는 프로그램 작성

In [21]:
N, M = map(int, input().split())
balls = list(map(int, input().split()))

num_of_case = 0
for i in range(N):
    for j in range(i+1, N):
        if balls[i] != balls[j]:
            num_of_case += 1
print(num_of_case)

25


### 해결 전략
무게가 같더라도 모두 다른 볼링공으로 취급하므로 경우의 수를 하나하나 세야한다.

# 무지의 먹방 라이브

In [29]:
food_times = list(map(int, input().split()))
dishes = len(food_times)

k = int(input())
idx = 0
for _ in range(k):
    while food_times[idx] == 0:
        idx = (idx + 1) % dishes

    food_times[idx] -= 1
    print(food_times)
    idx = (idx + 1) % dishes
print(idx + 1)

[2, 2, 3, 4]
[2, 1, 3, 4]
[2, 1, 2, 4]
[2, 1, 2, 3]
[1, 1, 2, 3]
[1, 0, 2, 3]
[1, 0, 1, 3]
[1, 0, 1, 2]
[0, 0, 1, 2]
[0, 0, 0, 2]
4


# 해결 전략
K번을 먹은 후의 다음 음식을 알아내는 것이므로 하나씩 10번 먹고 그 다음의 순서만 알아내면 된다.

# 럭키 스트레이트

In [31]:
S = list(map(int, input()))
half = len(S) // 2

if sum(S[:half]) == sum(S[half:]): print('LUCKY')
else: print('READY')

READY


### 해결 전략
절반씩 더하여 더한 값이 같은지 아닌지 비교

# 문자열 재정렬

주어진 문자열에서 왼쪽에는 알파벳 정렬, 오른쪽에는 각 정수들의 합을 이어서 출력

In [38]:
S = list(input())
alphabet = [a for a in S if a.isalpha()]
nums = sum(map(int, [n for n in S if n.isnumeric()]))
alphabet.sort()
result = ''.join(alphabet) + str(nums)
print(result)

AADDIJJJKKLSS20


### 해결 전략
그냥 나눠서 정렬, 더해서 str으로 이어붙였다.

# 문자열 압축

In [62]:
s = input()
len_s = len(s)
print(s)

len_results = []
for len_unit in range(1, len_s//2 + 1):
    result = ''
    compare_str = s[:len_unit]
    comp_deg = 1
    idx = len_unit

    while True:
        if compare_str == s[idx:idx+len_unit]:
            comp_deg += 1
        else:
            if comp_deg == 1:
                result += compare_str
            else:
                result += str(comp_deg) + compare_str
            compare_str = s[idx:idx+len_unit]
            comp_deg = 1

        idx += len_unit

        if idx + len_unit > len_s:
            if comp_deg == 1:
                result += compare_str
            else:
                result += str(comp_deg) + compare_str
            result += s[idx:]
            print(result)
            len_results.append(len(result))
            break

print(len_results)
print(min(len_results))

xababcdcdababcdcd
xababcdcdababcdcd
xababcdcdababcdcd
xababcdcdababcdcd
xababcdcdababcdcd
xababcdcdababcdcd
xababcdcdababcdcd
xababcdcdababcdcd
xababcdcdababcdcd
[17, 17, 17, 17, 17, 17, 17, 17]


# 자물쇠와 열쇠

In [137]:
import numpy as np

key = [[0, 0, 0],
       [1, 0, 0],
       [0, 1, 1]]

lock = [[1, 1, 1],
        [1, 1, 0],
        [1, 0, 1]]

open = [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]

M, N = 3, 3
padding = M-1
padded_lock = np.zeros((N+2*M-2, N+2*M-2), dtype=int)
padded_lock[M-1:N+M-1, M-1:N+M-1] = lock
print(padded_lock)

# 시계 반대 방향으로 90도 회전
def rotate(key):
    new_key = np.zeros((M, M), dtype=int)
    for i in range(M):
        for j in range(M):
            new_key[-j+(M-1)][i] = key[i][j]
    return new_key

# 4방향 모두에 대하여 구함
def solution(key, map):
    for _ in range(4):
        key = rotate(key)
        # convolution
        for i in range(M+N-1):
            for j in range(N+M-1):
                conv_result = padded_lock.copy()
                for k in range(M):
                    for l in range(M):
                        conv_result[i+k][j+l] = padded_lock[i+k][j+l] + key[k][l]
                print('conv_result')
                print(conv_result)

                # 만약 키가 딱 맞아서 돌아간다면 print false
                # print((conv_result[M-1:N+M-1, M-1:N+M-1] == open))
                if (conv_result[M-1:N+M-1, M-1:N+M-1] == open).all():
                    return True
    return False

print(solution(key, map))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 1]
 [0 0 1]
 [0 1 0]]
conv_result
[[0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
conv_result
[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 2 1 1 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
conv_result
[[0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 1 2 1 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
conv_result
[[0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0]
 [0 0 1 1 2 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
conv_result
[[0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 1 1 1 1 0]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
conv_result
[[0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 2 1 1 0 0]
 [0 1 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
conv_result
[[0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 2 1 0 