# 연구소

NxM의 크기의 격자가 주어진다. 이때 벽을 딱 3개 세울 수 있는데 <br>
벽을 세우고 이떄 바이러스가 퍼진 최종 국면에서 안전한 타일 최댓값을 구하는 문제

In [1]:
from copy import deepcopy
import itertools
from collections import deque

dx = [-1, 0, 1, 0]
dy = [0, -1, 0, 1]

def spread_virus(start, tmp):
    q = deque()
    q.append(start)

    while q:
        cur_pos = q.popleft()
        x, y = cur_pos[0], cur_pos[1]

        for i in range(4):
            nx, ny = x + dx[i], y + dy[i]
            if 0 <= nx < N and 0 <= ny < M:
                if tmp[nx][ny] == 0:
                    tmp[nx][ny] = 2
                    q.append((nx, ny))

def find_virus_position() -> list:
    """global 변수인 graph에 접근하여 virus들의 위치 정보를 담은 List return"""
    global graph, N, M

    virus_pos = []
    for r in range(N):
        for c in range(M):
            if graph[r][c] == 2:
                virus_pos.append((r, c))
    return virus_pos

N, M = map(int, input().split())
# graph = [[2, 0, 0, 0, 0, 0, 0, 2],
#          [2, 0, 0, 0, 0, 0, 0, 2],
#          [2, 0, 0, 0, 0, 0, 0, 2],
#          [2, 0, 0, 0, 0, 0, 0, 2],
#          [2, 0, 0, 0, 0, 0, 0, 2],
#          [0, 0, 0, 0, 0, 0, 0, 0],
#          [0, 0, 0, 0, 0, 0, 0, 0],
#          [0, 0, 0, 0, 0, 0, 0, 0]]
# graph = [[0, 0, 0, 0, 0, 0],
#          [1, 0, 0, 0, 0, 2],
#          [1, 1, 1, 0, 0, 2],
#          [0, 0, 0, 0, 0, 2]]
graph = [[2, 0, 0, 0, 1, 1, 0],
         [0, 0, 1, 0, 1, 2, 0],
         [0, 1, 1, 0, 1, 0, 0],
         [0, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 1, 1],
         [0, 1, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0]]
# graph = []
# for r in range(N):
#     graph.append(list(map(int, input().split())))

positions = [(r, c) for c in range(M) for r in range(N)]
iter_pos = list(itertools.combinations(positions, 3))
virus_pos = find_virus_position()

safe_areas = []
for list_of_3wall in iter_pos:
    tmp_graph = deepcopy(graph)

    for wall_pos in list_of_3wall:
        x, y = wall_pos[0], wall_pos[1]
        if tmp_graph[x][y] == 0:
            tmp_graph[x][y] = 1

    for virus_start in virus_pos:
        spread_virus(virus_start, tmp_graph)

    result = 0
    for i in tmp_graph: result += i.count(0)
    safe_areas.append(result)

print(max(safe_areas))

27


In [58]:
a = [[2, 1, 0, 0, 1, 1, 2],
    [1, 0, 1, 0, 1, 2, 2],
 [0, 1, 1, 0, 1, 2, 2],
 [0, 1, 0, 0, 0, 1, 2],
 [0, 1, 0, 0, 0, 1, 1],
 [0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0]]


s = a.count(0)
print()

0


In [4]:
import numpy as np

l = np.zeros((3, 3, 3))
print(l)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
None
